server:
  port: 7080
spring:
  application:
    name: app-eureka
banner:
  location: classpath:banner.starter
manager:
  version: V2018.10.12.0.0.1
logging:
  config: classpath:log/log4j2-spring-prod.xml
eureka:
  instance:
    hostname: ${spring.application.name}
    instance-id: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.instance-id}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 120000